### PR TITLE
[WIP]#57059475 implement bottom modal with country picker

### PR DESCRIPTION
**Pull request by dushimeemma**
#### What does this PR do?
design bottom modal with country picker
#### Description of Task to be completed?
- install country picker package
- create country picker widget
- create text input form field widget
#### How should this be manually tested?
- switch branch `git checkout ft-bottom-popup-view-57059475`
- run app `flutter run`
#### Any background context you want to provide?
- there no logic implementation yet
- the app is only running on `android` because there are some installed dependencies like `awesome_notifications` and `cloud_firestore` that are not running on `ios`
#### What are the relevant pivotal tracker stories?
[#57059475](https://github.com/yegobox/flipper-core/projects/1#card-57059475)
#### Screenshots (if appropriate)
Screen Shot 2021-03-24 at 11 36 46
Screen Shot 2021-03-25 at 06 03 17

### CODE REVIEW

**Review by richard457 — CHANGES_REQUESTED** [review]
The design should show both ios, web, desktop android screenshots.

**Review by richard457 — CHANGES_REQUESTED** [review]
This pull request can not be approved because of the following, the PR has a conflict with the new-design branch, the design should show design for android, ios, web, desktop, and android.

**Comment by richard457** [comment]
The PR should have screenshots of all supported devices to ensure that we are running on all platforms and also the bottom sheet should have a round corner as shown on the UI, +250 should not be shown as that's what the flag stands for. @dushimeemma

**Comment by richard457** [comment]
I can see the yellow ling beneath the text, this is a design mistake that also should be fixed.

**Comment by dushimeemma** [comment]
> I can see the yellow ling beneath the text, this is a design mistake that also should be fixed.

Which yellow one @richard457 ?

**Comment by dushimeemma** [comment]
> > I can see the yellow ling beneath the text, this is a design mistake that also should be fixed.

I think this issue is coming from the device I test the app from not in the codes.

**Comment by dushimeemma** [comment]
> again another PR that is addressing none of my comments above, why for example not seeing the screens of all platforms targeted?

@richard457  the reason why i have only android screenshot is that `awesome notification` dependency doesn't allow the app to start on ios.

**Comment by richard457** [comment]
> > again another PR that is addressing none of my comments above, why for example not seeing the screens of all platforms targeted?
> 
> @richard457 the reason why i have only android screenshot is that `awesome notification` dependency doesn't allow the app to start on ios.

Didn't we decide to remove it a couple of time why isn't removed?

**Comment by dushimeemma** [comment]
> > > again another PR that is addressing none of my comments above, why for example not seeing the screens of all platforms targeted?
> > 
> > 
> > @richard457 the reason why i have only android screenshot is that `awesome notification` dependency doesn't allow the app to start on ios.
> 
> Didn't we decide to remove it a couple of time why isn't removed?

It is used in many files, it a kind difficult for me to refactor all those files.

**Pull request merged**
